
USE RENTAL_CAR;


CREATE TABLE CAR(
	Id INT NOT NULL PRIMARY KEY,
	Model VARCHAR(100) NOT NULL,
	Power INT NOT NULL,
	Color VARCHAR(50) NOT NULL,
	Class VARCHAR (1) NOT NULL,
	Capacity INT NOT NULL,
	FuelConsumption real NOT NULL,
	IsAvailable BIT NOT NULL,
	Price INT NOT NULL
);

CREATE TABLE PHOTOS(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Car_Id INT NOT NULL FOREIGN KEY REFERENCES CAR(Id),
	Photo Image NOT NULL,
);

CREATE TABLE USERS(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Passport VARCHAR(10) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	CardNumber INT NOT NULL
);

CREATE TABLE PROFILE (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Password VARCHAR(50) NOT NULL UNIQUE,
	Login VARCHAR(50) NOT NULL UNIQUE,
	UserId INT NOT NULL FOREIGN KEY REFERENCES USERS(Id)
);


CREATE TABLE RENTAL_APPLICATIONS(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
	ProfileID INT NOT NULL FOREIGN KEY REFERENCES PROFILE(Id),
	CarId INT NOT NULL FOREIGN KEY REFERENCES CAR(Id)
);


DROP TABLE RENTAL_APPLICATIONS;
DROP TABLE PROFILE;
DROP TABLE PHOTOS;
DROP TABLE USERS;
DROP TABLE CAR;





